//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Tools.Deployer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Tools.Deployer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 部署“{0}”文件，总计执行了{1}次文件复制（成功{2}次；失败{3}次）。 的本地化字符串。
        /// </summary>
        internal static string Text_Deploy_CompleteInfo {
            get {
                return ResourceManager.GetString("Text.Deploy.CompleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”部署文件是不存在的。 的本地化字符串。
        /// </summary>
        internal static string Text_DeploymentFileNotExists {
            get {
                return ResourceManager.GetString("Text.DeploymentFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”目录是不存在的。 的本地化字符串。
        /// </summary>
        internal static string Text_DirectoryNotExists {
            get {
                return ResourceManager.GetString("Text.DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”文件删除失败。 的本地化字符串。
        /// </summary>
        internal static string Text_FileDeleteFailed {
            get {
                return ResourceManager.GetString("Text.FileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”文件删除成功。 的本地化字符串。
        /// </summary>
        internal static string Text_FileDeleteSucceed {
            get {
                return ResourceManager.GetString("Text.FileDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”文件是不存在的。 的本地化字符串。
        /// </summary>
        internal static string Text_FileNotExists {
            get {
                return ResourceManager.GetString("Text.FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的“{0}”是无效的参数格式。 的本地化字符串。
        /// </summary>
        internal static string Text_InvalidArgumentFormat {
            get {
                return ResourceManager.GetString("Text.InvalidArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定部署文件参数且当前目录下没有默认(.deploy)部署文件。 的本地化字符串。
        /// </summary>
        internal static string Text_MissingArguments {
            get {
                return ResourceManager.GetString("Text.MissingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示： 的本地化字符串。
        /// </summary>
        internal static string Text_Tips {
            get {
                return ResourceManager.GetString("Text.Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告： 的本地化字符串。
        /// </summary>
        internal static string Text_Warn {
            get {
                return ResourceManager.GetString("Text.Warn", resourceCulture);
            }
        }
    }
}
